name: docker-bake-multiarch

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/factoryai-droid

jobs:
  bake:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5

      - name: Set up QEMU (for ARM emulation)
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Bake (multi-arch, multi-target)
        uses: docker/bake-action@v6
        with:
          files: |
            ./docker-bake.hcl
          set: |
            IMAGE_NAME=${{ env.IMAGE_NAME }}
            *.labels.org.opencontainers.image.revision=${{ github.sha }}
            *.platform=linux/amd64,linux/arm64
          push: true
          provenance: true
          sbom: true
