name: Build and Push Multi-Arch Images

on:
  push:
    branches: [ main ]
    tags: ['*']
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ vars.DOCKERHUB_USERNAME }}/factoryai-droid

jobs:
  docker-build-multiarch:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Fetch Droid installer and extract DROID_VERSION
        id: version
        run: |
          set -euo pipefail
          curl -fsSL https://app.factory.ai/cli -o droid_installer.sh
          DROID_VERSION="$(grep -E '^VER=\"[^\"]+\"' droid_installer.sh | sed -E 's/^VER=\"([^\"]+)\".*/\1/')"
          echo "DROID_VERSION=${DROID_VERSION}"
          echo "DROID_VERSION=${DROID_VERSION}" >> "$GITHUB_ENV"

      - uses: actions/checkout@v5

      - name: Set up QEMU (for ARM emulation)
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Stamp build date (UTC)
        run: echo "BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV

      - name: Build & push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.DROID_VERSION }}
            ${{ env.IMAGE_NAME }}:latest
          build-args: |
            DROID_VERSION=${{ env.DROID_VERSION }}
          labels: |
            org.opencontainers.image.created=${{ env.BUILD_DATE }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=${{ env.DROID_VERSION }}
          provenance: true
          sbom: true
