name: Droid Release Sync (scheduled)

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Droid installer and extract DROID_VERSION
        id: version
        run: |
          set -euo pipefail
          curl -fsSL https://app.factory.ai/cli -o droid_installer.sh
          DROID_VERSION="$(grep -E '^VER=\"[^\"]+\"' droid_installer.sh | sed -E 's/^VER=\"([^\"]+)\".*/\1/')"
          echo "DROID_VERSION=${DROID_VERSION}"
          echo "DROID_VERSION=${DROID_VERSION}" >> "$GITHUB_ENV"

      - name: Checkout with full history using PAT
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_FACTORYAI_DROID_DOCKER }}

      # Workaround for https://github.com/actions/checkout/issues/1781 causing tags to be missing
      - name: Ensure tags are available
        run: git fetch --tags --force

      - name: Check if tag DROID_VERSION exists
        id: check_tag
        run: |
          if git rev-parse -q --verify "refs/tags/${DROID_VERSION}" >/dev/null; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
            echo "✅ Tag '${DROID_VERSION}' already exists."
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
            echo "⚙️ Tag '${DROID_VERSION}' does not yet exist..."
          fi

      - name: Create & push tag DROID_VERSION if missing (uses PAT from checkout)
        if: steps.check_tag.outputs.exists == 'false'
        run: |
          git tag "${DROID_VERSION}"
          git push origin "refs/tags/${DROID_VERSION}"
          echo "✅ Created and pushed tag '${DROID_VERSION}'."
