name: Tag default-branch HEAD if missing

on:
  schedule:
    - cron: "0 6 * * *"   # adjust as needed
  workflow_dispatch:

permissions:
  contents: write  # needed to push tags

env:
  # Provide DROID_VERSION via Repo → Settings → Variables, or as env in a caller.
  DROID_VERSION: ${{ vars.DROID_VERSION || env.DROID_VERSION }}

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Assert DROID_VERSION provided
        run: |
          if [ -z "${DROID_VERSION}" ]; then
            echo "❌ DROID_VERSION is not set."
            exit 1
          fi
          echo "DROID_VERSION=${DROID_VERSION}"

      - name: Checkout with full history
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Workaround for https://github.com/actions/checkout/issues/1781 causing tags to be missing
      - name: Ensure tags are available
        run: git fetch --tags --force

      - name: Check if tag DROID_VERSION exists
        id: check_tag
        run: |
          if git rev-parse -q --verify "refs/tags/${DROID_VERSION}" >/dev/null; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
            echo "✅ Tag '${DROID_VERSION}' already exists."
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
            echo "⚙️ Tag '${DROID_VERSION}' does not yet exist..."
          fi

      - name: Create & push tag DROID_VERSION if missing
        if: steps.check_tag.outputs.exists == 'false'
        env:
          GIT_AUTH_TOKEN: ${{ secrets.PAT_FACTORYAI_DROID_DOCKER }}
        run: |
          git tag "${DROID_VERSION}"
          git push origin "refs/tags/${DROID_VERSION}"
          echo "✅ Created and pushed tag '${DROID_VERSION}'."
