name: On New Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  react-to-release:
    runs-on: ubuntu-latest
    env:
      RELEASE_NAME: ${{ github.event.release.name }}
      RELEASE_TAG: ${{ github.event.release.tag_name }}

    steps:
      - name: Print release info
        run: |
          echo "🚀 New release detected!"
          echo "RELEASE_NAME=${RELEASE_NAME}"
          echo "RELEASE_TAG=${RELEASE_TAG}"
