name: On New Tag

on:
  push:
    tags: ['*']

permissions:
  contents: read

jobs:
  react-to-tag:
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{ github.ref_name }}
      REF: ${{ github.ref }}

    steps:
      - name: Print tag info
        run: |
          echo "🚀 New tag detected!"
          echo "TAG_NAME=${TAG_NAME}"
          echo "REF=${REF}"
