name: On New Tag

on:
  push:
    tags: ['*']

permissions:
  contents: read

jobs:
  react-to-tag:
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{ github.event.tag.name }}
      TAG_TAG: ${{ github.event.tag.tag_name }}

    steps:
      - name: Print tag info
        run: |
          echo "🚀 New tag detected!"
          echo "TAG_NAME=${TAG_NAME}"
          echo "TAG_TAG=${TAG_TAG}"
